# Generated by Django 2.2.2 on 2019-06-16 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='workgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myztree.workgroup', verbose_name='pId')),
            ],
            options={
                'verbose_name': 'workgroup',
                'verbose_name_plural': 'workgroup',
                'db_table': 'myztree_workgroup',
            },
        ),
        migrations.CreateModel(
            name='workgroup_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wkgroupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myztree.workgroup')),
            ],
            options={
                'verbose_name': 'workgroup_user',
                'verbose_name_plural': 'workgroup_user',
                'db_table': 'myztree_workgroup_user',
            },
        ),
    ]
