# Generated by Django 2.1.1 on 2020-05-19 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_title', models.CharField(default='赶紧给这个笔记取个名字吧！', max_length=50, verbose_name='笔记标题')),
                ('N_content', models.TextField(verbose_name='笔记内容')),
                ('N_brief', models.CharField(blank=True, max_length=100, null=True, verbose_name='笔记摘要')),
                ('N_idea', models.CharField(blank=True, max_length=200, null=True, verbose_name='笔记想法')),
                ('N_pic', models.ImageField(null=True, upload_to='pictures/%Y/%m/%d/', verbose_name='笔记插图')),
                ('N_istop', models.IntegerField(blank=True, null=True, verbose_name='置顶级别')),
                ('N_create_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='创建时间')),
                ('N_update_time', models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('N_status', models.IntegerField(default=1, null=True, verbose_name='笔记状态')),
            ],
            options={
                'verbose_name': '笔记信息',
                'verbose_name_plural': '笔记信息',
            },
        ),
    ]
