# Generated by Django 2.1.1 on 2020-05-19 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
        ('articles', '0002_auto_20200519_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='N_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='N_parent_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='notes.Note', verbose_name='父节点'),
        ),
        migrations.AddField(
            model_name='note',
            name='reference',
            field=models.ManyToManyField(blank=True, null=True, to='articles.Article', verbose_name='相关文章'),
        ),
    ]
