# Generated by Django 2.1.1 on 2020-05-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200519_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='reference',
        ),
        migrations.AlterField(
            model_name='note',
            name='N_parent_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.Note', verbose_name='父节点'),
        ),
    ]
