# Generated by Django 2.1.1 on 2020-05-24 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(default='', max_length=50, verbose_name='文章标题')),
                ('a_time', models.DateTimeField(verbose_name='文章时间')),
                ('a_source', models.CharField(default='', max_length=50, verbose_name='文章来源')),
                ('a_author', models.CharField(default='', max_length=30, verbose_name='文章作者')),
                ('a_content', models.TextField(verbose_name='文章内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2020, 5, 24, 8, 47, 26, 810782), verbose_name='添加时间')),
                ('a_status', models.IntegerField(default=1, verbose_name='文章状态')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=32, unique=True, verbose_name='订阅源名称')),
                ('F_URL', models.CharField(max_length=64, unique=True, verbose_name='订阅源URL')),
                ('F_status', models.IntegerField(default=1, verbose_name='订阅源状态')),
                ('F_icon', models.ImageField(blank=True, null=True, upload_to='RSSicons/%Y/%m/%d/', verbose_name='订阅源图标')),
                ('Subscription_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='订阅时间')),
            ],
            options={
                'verbose_name': '订阅源信息',
                'verbose_name_plural': '订阅源信息',
            },
        ),
    ]
