# Generated by Django 2.1.1 on 2020-05-22 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200519_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 21, 24, 14, 142219), verbose_name='添加时间'),
        ),
    ]
